# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef93ec2a01415fc1de3489c94b3a950d0eecdc0b9bd62a9542f467c2b1922ec37c1f82310fffcbdd38ab54bdc645eb2857228232eddda1a15ef7c4244fdd8609

test:
  secret_key_base: 260f512a8180cdc35ce949cbcdbff57a7133e82341a1290027a522d39f4ea9cf09f3791bb37790cac715c928bd0a1c73b49b0d171716d5d43f989ed4febdc930

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
